languageCode = "en-us"
title = "Hao and Mia"
baseurl = "https://haoandmia.com"
theme = "dimension"

[params]
  title = "Hao and Mia"
  description = '<!--[-->We are getting married!!! <!--]--><br />
                <!--[-->July 8th - 4pm - 1314 W Randolph St. Chicago, IL 60607<!--]-->'
  logo = "fa-heart-o"
  copyright = "Untitled"
  apiEndpoint = "http://localhost:8000"
  # apiEndpoint = "https://guests.haoandmia.com"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.brideparty]]
  name = "Anna Choi"
  title = "Maid of Honor | Bad @$$ Math Teacher in Detroit, MI"
  story = "It all started in 6th grade with one simple question, “Are you Korean?”, in the gym locker room. They quickly became best friends who were inseparable as they lived down the street together and had all the same classes. Their favorite snacks quickly became pizza rolls, pop and chips in Mia’s american household or rice with soy sauce at Anna’s (Mia eventually grew to love all korean food and can eat kimchi straight from the jar). Anna brought Mia to youth group where they were able to grow together in their love for Jesus throughout their formative years to the present. Their friendship turned into sistership -which included making fun of each other incessantly, making each other cry but also sharing their deepest fears, praying together and being there through the hardest of times. Anna has played a huge part of having Mia develop “thick skin” and has shown her what it means to be loved and accepted unconditionally."
  photo = "anna.jpg"

[[params.brideparty]]
  name = "Sylvia Cho"
  title = "Maid of Honor | Digital merchandiser and Design Goddess"
  story = "Sylvia and Mia met at GRIP Outreach For Youth - a Christian organization that’s mission is father the fatherless. At the time they were the only two Korean girls there and had recognized each other from high school youth group. Sylvia quickly warmed Mia’s heart by her thoughtfulness and silliness - making her laugh at all of Sylvia’s quirky sayings and stories. They had a bond - both for wanting to love others but also to be genuine and authentic in their love for God. Their friendship was proven true when Sylvia convinced Mia that she had an Adam’s Apple - only to have Mia freak out and Google, “Can women have Adam’s Apple?” and Sylvia LOL’ing that she had fooled her friend. You can find Sylvia and Mia throat punching or making fun of each other, or sharing their deepest thoughts and hopes over good food. Sylvia has played a huge role of showing Mia to fully embrace who she is- weirdness and craziness and all."
  photo = "sylvia.jpg"

[[params.brideparty]]
  name = "Esther Lee"
  title = "Bridesmaid | Intellect that creates PD opportunities for CPS teachers via The Fund"
  story = "Esther and Mia met during the time that there were two genuine questions to know what type of person you were: 1) Are you team N’Sync or team Backstreet Boys? 2) Michelle Kwan or Tara Lipinski? They quickly became friends and their friendship flourished post college where they found themselves together as they figured their 20s out. Esther’s heart is one of gold - Mia still has a scrapbook that Esther made highlighting the retreat that marks Mia’s spiritual birthday. Esther has been there to feed and comfort Mia when Mia chipped her front tooth at a Christmas party trying to do a yoga pose (she did this all without ever laughing at Mia - something Mia could not do). Esther has a kindness that is deep and true; and Mia is grateful to have a friend that challenges her to keep up with politics and world issues. Esther has taught Mia what kindness looks like."
  photo = "esther.jpg"

[[params.brideparty]]
  name = "Alexandra Sundet"
  title = "Bridesmaid | Sales & Marketing Guru at New Moms"
  story = "Alexandra and Mia met at UW-Madison’s infamous Halloween festivities - Alexandra was sporting a trashy housewife costume and Mia was dressed in a little boy Spiderman’s outfit that went to came up to her shins. They quickly realized that they had a unique sense of humor and have been laughing together  since the summer of 2008. Mia was grateful to have met Allie through a time when she was struggling a bit and is so blessed to see how much both of them have grown in their faith since the time they first met. Allie and Mia have been roommates for seven years and became family to one another. They have been together through the best time in their 20’s to the times when that make you realize just how hard your 20’s are. Allie has been there to ask Mia the tough questions in a loving way as well as being there when Mia has been at her absolute worst. You can often find Allie and Mia improvising and making up stories that have them in tears - from laughter. You can try to enter the conversation but will probably be lost within the first two minutes b/c they have shared so much of their life together. Allie has shown Mia what it is to be loved."
  photo = "allie.jpg"

[[params.brideparty]]
  name = "Laura Swanson"
  title = "Bridesmaid | Design Master at Big Fancy Law Firm"
  story = "Laura and Mia met on Laura’s first day of their internship where Mia was tasked with training Laura how to listen to voicemails. To both of the them, they realized the silliness of this task but both went along with it. Their internship would then have them travel and work 100+ hours a week and they quickly learned that they would food soul mates- they would both want to  items on the menu to find out the other wanted the same items and would split them, always. Their bond over food developed into realizing that they were loyal buds who sincerely cared about each other. Laura would be Mia’s adventure buddy - getting her to try new things for the first time - like biking in the streets of Chicago (no easy task!). Laura was the friend who held her hair when Mia got super seasick on a sailboat and was puking off the boat (and this was supposed to be a date for Laura). Laura is the friend who Mia would hangout with on the weekends for half of decade. They have shared many wine and Thai nights over conversation and jokes. Laura has taught Mia how to use Instagram and how to embrace and to face her fears and try new things that may seem scary!"
  photo = "laura.jpg"

[[params.brideparty]]
  name = "Cosi Schreiber"
  title = "Bridesmaid | Awesome Producer for Super Cool Commercials"
  story = "Cosi and Mia met on their first day of Orientation at an internship that they would soon realize would monopolize their lives for half of a year. They endured waking up at 4am today after going to bed well after midnight and doing manual labor for hours during the day. They survived driving a “gator” (motorized cart) down a race course only to realize they would drive where runners were coming from the opposite direction. Instead of freaking out, they both cheered on the runners as if this was planned all along. Cosi has shown up (literally as Cosi has lived a plane ride away for much of their friendship) in Mia’s life during some of her biggest triumphs and hardships. Cosi came to town after a breakup that was incredibly hard to get through - she has helped throw a baby shower for Sade - using her amazing decorating and baking skills. Cosi has one of the largest vocabularies of anyone Mia has ever met and has been her graduate school personal statement editor. Cosi spent hours helping Mia draft her personal statement -both in fleshing out ideas but also freeing it from many grammatical errors. They have shared many laughs and arm punches as Mia has learned to give people a proper amount of personal space (all thanks to Cosi). Cosi has encouraged Mia and taught Mia (by how Cosi lives her life) to continue to pursue her dreams and fight even when the going gets tough."
  photo = "cosi.jpg"

[[params.brideparty]]
  name = "Courtney Pergal"
  title = "Bridesmaid | (Making a) Child’s Life (Better) Specialist"
  story = "It all began in college when they would meet at Mickey’s Diner through mutual friends. Mia remembers Courtney’s kind and beautiful spirit from the first time she met Courtney. Courtney has been a huge support to Mia throughout college and continues to be one of her biggest cheerleaders. Courtney has listened to Mia as she has shared some of her biggest struggles and has been there to rejoice alongside Mia during the biggest joys. Courtney is a woman of her word - a woman who constantly strives to love Jesus more and more and a woman who is genuine and kind. Courtney is humble and for anyone who comes in contact knows instantly at how beautiful she is inside and out. Mia often made fun of Courtney’s pajama pant length that even to this day, Courtney remembers and laughs about it - letting Mia be the little bully that she is (hopefully it all comes off as love!). Courtney has shown Mia what patience looks like - patience in waiting on God, patience with people and patience in life."
  photo = "courtney.jpg"

[[params.brideparty]]
  name = "Dana Swedberg"
  title = "Bridesmaid | Pre-K Teacher by Day / Pure Romance Consultant by Night ;)"
  story = "Dana and Mia met their freshman year at the University of Wisconsin-Madison where they instantly connected in their bible study small group. Dana and Mia became best of friends and were lucky enough to be actual roommates their senior year where they shared bunk beds as grown adults. Dana convinced Mia to sign up for ballroom dancing where Mia’s hands were always sweaty and her feet not quite doing the right moves. Mia may have fell in class and Dana may have been cracking up incessantly. Mia caught Dana filling the dishwasher with Comet for third time! You would often find Dana and Mia having heart to heart talks in their bunk beds, OR leave their (messy!) room to hangout (bug!) Courtney and read FML’s for hours on end. Whenever Mia was extremely stressed or sad, Dana would make Mia feel better by singing or encouraging Mia. Dana has taught Mia how to laugh and take life a little less seriously."
  photo = "dana.jpg"

[[params.brideparty]]
  name = "Sherine Teymour"
  title = "Bridesmaid | Light design and furniture creation master in California"
  story = "Mia and Sherine met at summer camp in the third grade through our friend Sheila. Mia and Sherine started going to school together in junior high and instantly clicked as close friends. Sherine is the friend Mia knows she could call at any hour for anything (and the feeling is mutual). They are like sisters in that way. They have shared their life experiences together - some of the richest moments and some of the saddest moments. Sherine and Mia have each other’s back and while they are different people, they often connect at the heart. Sherine has encouraged Mia to pursue my dreams both in word and by example - she pursued a master's program after finishing a rigorous undergraduate degree and worked in different major cities. Sherine wouldn’t let Mia give up on my dreams either. Sherine lights up a room with her laughter and love for people. Sherine has shown Mia what love looks like and to never give up no matter what happens in life!"
  photo = "sherine.jpg"

[[params.groomparty]]
  name = "Jian Tian"
  title = "Best Man | Software Engineer at University of Chicago"
  story = "Jian and Hao met at Vanderbilt.  They both served in the Intervarsity fellowship together, and would often talk about life and God. After college, Jian and Hao stayed in touch, and through one phone call, they convinced each other to move to Chicago together.  And their friendship has only deepened since then."
  photo = "jian.jpg"

[[params.groomparty]]
name = "Sen (Mark) Ma"
title = "Groomsmen | FPGA Wizard at Micron Technology"
story = "Mark was a first-year PHD student from China when Hao was assigned to the same computer lab as him. Mark not only helped Hao with every computer engineering question he had, he also sparked Hao's curiosity to pursue more deeply in computer science.  Mark seems to have infinite patience when comes to teaching others, and his sense of curiosity is inspirational."
photo = "mark.jpg"

[[params.groomparty]]
name = "David Goodwin"
title = "Groomsmen | Speaker of Wisdom & Recent Graduate of McCormick Seminary"
story = "Hao met David when he was carrying a bag of donated clothes to church. Shortly after, David invited me to his small group.  It just so happens to be Mia's small group as well.  David was Hao's confidant when he was thinking about pursuing Mia, and helped him process his thoughts.  Even after Mia and Hao started dating, David was there as a trusted friend to speak wisdom into their relationship."
photo = "david.jpg"

[[params.groomparty]]
name = "Matthew Luo"
title = "Groomsmen | Brother & Swimmer (as fast as a fish)"
story = "Hao and Matthew are 15 years apart.  Hao still remembers when Matthew was born.  Now, Matthew is soon turning 14.  Matthew is quiet and stoic most days, but when it comes to Swimming or Minecraft, he can go nonstop.  Matthew is talented in writing, and would often come up with clever puzzles for our whole family to solve."
photo = "matthew.jpg"
